services:
  # Servicio de la aplicación Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: formulario-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - laravel-network
    depends_on:
      - db

  # Servicio Nginx
  nginx:
    image: nginx:alpine
    container_name: formulario-nginx
    restart: unless-stopped
    ports:
      - "8888:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel-network
    depends_on:
      - app

  # Servicio MySQL
  db:
    image: mysql:8.0
    container_name: formulario-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: laravel
      MYSQL_USER: laravel
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel-network

  # Servicio PhpMyAdmin (opcional)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: formulario-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    networks:
      - laravel-network
    depends_on:
      - db

# Redes
networks:
  laravel-network:
    driver: bridge

# Volúmenes
volumes:
  dbdata:
    driver: local
